# Generated by Django 5.2.4 on 2025-07-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defect_detection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadHistory',
        ),
    ]
